name: ds_future
description: Deadly simple future methods
version: 1.0.3
repository: https://github.com/uac-nhan-nguyen/ds_future
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.22.1

